pipelines:
  "docker-ideide":
    group: ide
    label_template: "${git[:8]}"
    materials:
      git:
        git: "git@git.ai-traders.com:ide/docker-ideide.git"
        branch: master
    stages:
      - style:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
                - small
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks verify_version
      - build_ubuntu:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
                - small
              tasks:
                # All those tasks happen on 1 go-agent, thus there is no need
                # to docker push the image before it's tested.
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest
                # No publish. There is automated docker build.
      - build_alpine:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
                - small
              tasks:
                # All those tasks happen on 1 go-agent, thus there is no need
                # to docker push the image before it's tested.
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_alpine
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest_alpine
      - release:
          clean_workspace: true
          jobs:
            code:
              resources:
                - docker
                - small
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks release
