#!/bin/bash

set -e
if [[ ! -f ./releaser ]];then
  wget http://http.archive.ai-traders.com/releaser/0.3.2/releaser
fi
source ./releaser
releaser_init

version_file="./image/etc_ide.d/variables/60-variables.sh"

function verify_version_not_released {
  source "${version_file}"
  if [[ $(git tag | grep "${this_image_tag}" -c) -ne 0 ]]; then
    echo "git tag: ${this_image_tag} exists already, please bump version in "\
    "${version_file}"
    exit 1
  fi
  changelog_version=$(get_last_version_from_changelog "${changelog_file}")
  if [[ $(git tag | grep "${changelog_version}" -c) -ne 0 ]]; then
    echo "git tag: ${changelog_version} exists already, please bump version in "\
    "changelog file"
    exit 1
  fi
}


command="$1"
case "${command}" in
  bump)
    new_version="$2"
    if [[ -z "${new_version}" ]];then
      source "${version_file}"
      old_version="${this_image_tag}"
      new_version="$(bump_patch_version ${old_version})"
    fi
    locally_bump_version_in_versionfile "export this_image_tag=" "${version_file}" "${new_version}"
    locally_bump_version_in_changelog "${changelog_file}" "${new_version}"
    exit $?
    ;;
  verify_version)
      verify_version_not_released
      exit $?
      ;;
  build)
      # 1. This is an automated build on docker hub, so we cannot have complicated
      # build script or use --build-arg.
      # 2. Also, since it is a public github repo, the non-release commands must
      # be invocable for anyone.
      source "${version_file}"
      cd image
      docker build -t ${this_image_name}:${this_image_tag} --rm .
      exit $?
      ;;
  build_alpine)
      source "${version_file}"
      cd image
      docker build -f DockerfileAlpine -t ${this_image_name}-alpine:${this_image_tag} --rm .
      exit $?
      ;;
  itest)
      source "${version_file}"
      image="${this_image_name}:${this_image_tag}"
      echo "Testing image: ${image}"
      echo "IDE_DOCKER_IMAGE=${image}" > Idefile.to_be_tested
      echo "IDE_IDENTITY=$(pwd)/test/integration/ide_identities/full" >> Idefile.to_be_tested
      echo "IDE_WORK=$(pwd)/test/integration/ide_work" >> Idefile.to_be_tested
      echo "IDE_DOCKER_OPTIONS=\"--privileged\"" >> Idefile.to_be_tested
      time bats "$(pwd)/test/integration/bats"
      exit $?
      ;;
  itest_alpine)
      source "${version_file}"
      image="${this_image_name}-alpine:${this_image_tag}"
      echo "Testing image: ${image}"
      echo "IDE_DOCKER_IMAGE=${this_image_name}-alpine:${this_image_tag}" > Idefile.to_be_tested
      echo "IDE_IDENTITY=$(pwd)/test/integration/ide_identities/full" >> Idefile.to_be_tested
      echo "IDE_WORK=$(pwd)/test/integration/ide_work" >> Idefile.to_be_tested
      echo "IDE_DOCKER_OPTIONS=\"--privileged\"" >> Idefile.to_be_tested
      time bats "$(pwd)/test/integration/bats"
      exit $?
      ;;
  release)
      verify_version_not_released
      git tag "${this_image_tag}"
      # push git tag
      git push origin "${this_image_tag}"
      exit $?
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
